### ISSUE TITLE
Overloading?

### ISSUE THREAD

**Issue by tsibley** [Klortho/Physics-Unit#30]
Would you be open to using operator overloading for Physics::Unit and Physics::Unit::Scalar objects?

At the very least, it'd be nice to overload stringification to call `ToString`, but division, multiplication, etc. could all be supported.

**Comment by Klortho** [comment]
That's a fine idea.  But I haven't worked on this repo in a long time, and not sure when I'd have time to. Pull requests welcome, of course.

**Comment by tsibley** [comment]
Well now, never say never I guess! :upside_down_face:
